# Generated by Django 5.2.14 on 2026-05-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('SEASONAL', 'Seasonal'), ('CUSTOM', 'Custom')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Price multiplier (1.0 = no change, 1.3 = 30% increase).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'db_table': 'pricing_rules',
                'ordering': ['start_date'],
            },
        ),
    ]
