# Generated by Django 5.2.14 on 2026-05-13 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_address', models.TextField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotels.contactinfo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelMinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_prices', to='hotels.hotel')),
            ],
            options={
                'db_table': 'hotel_min_prices',
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city'], name='idx_hotel_city'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['active'], name='idx_hotel_active'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['owner'], name='idx_hotel_owner'),
        ),
        migrations.AddIndex(
            model_name='hotelminprice',
            index=models.Index(fields=['hotel', 'date'], name='idx_hmp_hotel_date'),
        ),
        migrations.AddIndex(
            model_name='hotelminprice',
            index=models.Index(fields=['date', 'min_price'], name='idx_hmp_date_price'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelminprice',
            unique_together={('hotel', 'date')},
        ),
    ]
