# Generated by Django 5.2.14 on 2026-05-13 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField()),
                ('surge_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Pricing multiplier for this date (1.0 = normal, 1.5 = 50% surge).', max_digits=5)),
                ('closed', models.BooleanField(default=False, help_text='If True, this date is blocked from booking.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotels.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['room', 'date'], name='idx_inv_room_date'), models.Index(fields=['hotel', 'date'], name='idx_inv_hotel_date'), models.Index(fields=['date'], name='idx_inv_date')],
                'unique_together': {('room', 'date')},
            },
        ),
    ]
